name: Release

on:
  workflow_dispatch:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.18'
    - name: Set version env
      run: echo "CI_VERSION=$(cat VERSION | awk NF)" >> $GITHUB_ENV
    - name: Run build
      run: make
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    - name: Log into registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        registry: docker.io
        username: virtualzone
        password: ${{ secrets.CI_REGISTRY_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        push: true
        tags: |
          virtualzone/http-redirect:${{ env.CI_VERSION }}
          virtualzone/http-redirect:latest
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new
    - name: Create a GitHub release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ env.CI_VERSION }}
        name: ${{ env.CI_VERSION }}
        artifacts: "build/http-redirect_*"